version: "3.9"

services:
  postgres:
    image: postgis/postgis:16-3.4  
    environment:
      POSTGRES_USER: stc
      POSTGRES_PASSWORD: stc
      POSTGRES_DB: gamanagodb
    ports:
      - "5432:5432" # change the left side if 5432 is used on your Mac
    volumes:
       - pgdata:/var/lib/postgresql/data
    # Auto-run on first init
       - ../db/schemas/enable_postgis.sql:/docker-entrypoint-initdb.d/1_enable_postgis.sql
       - ../db/seeds/demo_stops.sql:/docker-entrypoint-initdb.d/2_demo_stops.sql

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  profile-agent:
    build:
      context: ../apps/agents/profile-personalizer # ← match your folder name
    environment:
      DATABASE_URL: postgres://onella:onella_pw@postgres:5432/gamanagodb
      PORT: "8001"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8001"
    volumes:
      - ../apps/agents/data-aggregator:/app   # bind mount your code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    restart: unless-stopped

  route-optimizer:
    build:
      context: ../apps/agents/route-optimizer
    environment:
      DATABASE_URL: postgres://onella:onella_pw@postgres:5432/gamanagodb
      PORT: "8002"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8002:8002"
    volumes:
      - ../apps/agents/route-optimizer:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
    restart: unless-stopped

  disruption-manager:
    build: ../apps/agents/disruption-manager
    env_file: ../.env.example
    depends_on:
      - redis
      - postgres
    ports:
      - "8003:8003"

  profile-personalizer:
    build: ../apps/agents/profile-personalizer
    env_file: ../.env.example
    depends_on:
      - postgres
    ports:
      - "8004:8004"

  fare-optimizer:
    build: ../apps/agents/fare-optimizer
    env_file: ../.env.example
    depends_on:
      - postgres
    ports:
      - "8005:8005"

  language-accessibility:
    build: ../apps/agents/language-accessibility
    env_file: ../.env.example
    depends_on:
      - postgres
    ports:
      - "8006:8006"

  local-knowledge:
    build: ../apps/agents/local-knowledge
    env_file: ../.env.example
    depends_on:
      - postgres
    ports:
      - "8007:8007"

  web:
    build: ../apps/web
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://onella:onella_pw@postgres:5432/gamanagodb
      PROFILE_AGENT_URL: http://profile-agent:8001
      ROUTE_AGENT_URL: http://route-optimizer:8002
      SEED_USER_ID: 1042c8a5-81b8-459d-a1fd-6d7f9ebc097a
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "3001:3000"
    command: npm run dev -- -p 3000 -H 0.0.0.0
    volumes:
     - ../apps/web:/app
      - /app/node_modules
    depends_on:
      - gateway
    volumes:
     - ../apps/web:/app

volumes:

  pgdata:
