version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: onella
      POSTGRES_PASSWORD: onella_pw
      POSTGRES_DB: gamanagodb
    ports:
      - "5432:5432" # change the left side if 5432 is used on your Mac
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onella -d gamanagodb || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  profile-agent:
    build:
      context: ../apps/agents/profile-personalizer # ← match your folder name
    environment:
      DATABASE_URL: postgres://onella:onella_pw@postgres:5432/gamanagodb
      PORT: "8001"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8001"

  route-optimizer:
    build:
      context: ../apps/agents/route-optimizer
    environment:
      DATABASE_URL: postgres://onella:onella_pw@postgres:5432/gamanagodb
      PORT: "8002"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8002:8002"

  web:
    build:
      context: ../apps/web 
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://onella:onella_pw@postgres:5432/gamanagodb
      PROFILE_AGENT_URL: http://profile-agent:8001
      ROUTE_AGENT_URL: http://route-optimizer:8002
      SEED_USER_ID: 1042c8a5-81b8-459d-a1fd-6d7f9ebc097a
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "3001:3000"
    command: npm run dev -- -p 3000 -H 0.0.0.0
    volumes:
     - ../apps/web:/app
      - /app/node_modules
    depends_on:
      - profile-agent
      - route-optimizer
      - postgres

volumes:
  pgdata:
